#!/usr/bin/env bash
set -e

# Create the database document_vector
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
# SELECT 'CREATE DATABASE document_vector'
# WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'document_vector')\gexec
# EOSQL

# Enable vector extension in the document_vector database
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "document_vector" <<-EOSQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE EXTENSION IF NOT EXISTS vector;
EOSQL

# Create table for storing document embeddings
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "document_vector" <<-EOSQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE TABLE IF NOT EXISTS document_embedding  (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    metadata JSONB,
    contents TEXT,
    embedding VECTOR(1536)
);
EOSQL

# Create table for storing web site embeddings
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "document_vector" <<-EOSQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE TABLE IF NOT EXISTS web_embedding  (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url TEXT,
    chunk_index INT,
    title TEXT,
    summary TEXT,
    contents TEXT,
    metadata JSONB,
    embedding VECTOR(1536)
);
EOSQL