#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
SELECT 'CREATE DATABASE document_vector'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'document_vector')\gexec
EOSQL

# Enable vector extension in the document_vector database
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "document_vector" <<-EOSQL
# CREATE EXTENSION IF NOT EXISTS vector CASCADE;
# EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "document_vector" <<-EOSQL
CREATE TABLE IF NOT EXISTS document_embedding  (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    metadata JSONB,
    contents TEXT,
    embedding VECTOR(1536)
);
CREATE INDEX document_embedding_idx ON document_embedding USING diskann (embedding vector_cosine_ops);
EOSQL
